using AmtocBots.Api.Models;
using System.Text;
using System.Text.Json;

namespace AmtocBots.Api.Services.OpenClaw;

/// <summary>
/// Builds an OpenClaw JSON5 configuration from a BotInstance + its ChannelConfigs.
/// The resulting string is written to the Docker volume via DockerService.WriteConfigVolumeAsync.
/// </summary>
public sealed class OpenClawConfigBuilder
{
    public string Build(BotInstance instance, IEnumerable<ChannelConfig> channels, string bearerToken)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by AmtocBots Manager. Edit via the UI.");
        sb.AppendLine("{");
        sb.AppendLine($"  identity: {{ name: {Json(instance.Name)}, theme: \"helpful assistant\", emoji: \"🤖\" }},");
        sb.AppendLine("  agent: {");
        sb.AppendLine("    workspace: \"/root/.openclaw/workspace\",");
        sb.AppendLine("    model: {");
        sb.AppendLine($"      primary: {Json(instance.CurrentModel)},");
        sb.AppendLine("    },");
        sb.AppendLine("  },");
        sb.AppendLine("  channels: {");

        foreach (var ch in channels.Where(c => c.IsEnabled))
        {
            var cfg = JsonDocument.Parse(ch.ConfigJson).RootElement;
            switch (ch.ChannelType)
            {
                case "telegram":
                    AppendTelegram(sb, cfg);
                    break;
                case "whatsapp":
                    AppendWhatsApp(sb, cfg);
                    break;
                case "discord":
                    AppendDiscord(sb, cfg);
                    break;
                case "slack":
                    AppendSlack(sb, cfg);
                    break;
            }
        }

        sb.AppendLine("  },");
        sb.AppendLine("  gateway: {");
        sb.AppendLine("    port: 18789,");
        sb.AppendLine("    auth: {");
        sb.AppendLine($"      tokens: [{Json(bearerToken)}],");
        sb.AppendLine("    },");
        sb.AppendLine("  },");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendTelegram(StringBuilder sb, JsonElement cfg)
    {
        sb.AppendLine("    telegram: {");
        sb.AppendLine($"      token: {Json(cfg.TryGet("token"))},");
        if (cfg.TryGetProperty("allowFrom", out var af))
            sb.AppendLine($"      allowFrom: {af},");
        sb.AppendLine("    },");
    }

    private static void AppendWhatsApp(StringBuilder sb, JsonElement cfg)
    {
        sb.AppendLine("    whatsapp: {");
        if (cfg.TryGetProperty("allowFrom", out var af))
            sb.AppendLine($"      allowFrom: {af},");
        sb.AppendLine("    },");
    }

    private static void AppendDiscord(StringBuilder sb, JsonElement cfg)
    {
        sb.AppendLine("    discord: {");
        sb.AppendLine($"      token: {Json(cfg.TryGet("token"))},");
        if (cfg.TryGetProperty("guildId", out var g))
            sb.AppendLine($"      guildId: {Json(g.GetString())},");
        if (cfg.TryGetProperty("allowChannels", out var ac))
            sb.AppendLine($"      allowChannels: {ac},");
        sb.AppendLine("    },");
    }

    private static void AppendSlack(StringBuilder sb, JsonElement cfg)
    {
        sb.AppendLine("    slack: {");
        sb.AppendLine($"      appToken: {Json(cfg.TryGet("appToken"))},");
        sb.AppendLine($"      botToken: {Json(cfg.TryGet("botToken"))},");
        if (cfg.TryGetProperty("allowChannels", out var ac))
            sb.AppendLine($"      allowChannels: {ac},");
        sb.AppendLine("    },");
    }

    private static string Json(string? value) =>
        value is null ? "null" : JsonSerializer.Serialize(value);
}

file static class JsonElementExtensions
{
    public static string? TryGet(this JsonElement el, string prop) =>
        el.TryGetProperty(prop, out var v) ? v.GetString() : null;
}
